# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo add-apt-repository ppa:opencpu/poppler -y
  - sudo apt-get update -q
  - sudo apt-get install libpoppler-cpp-dev

after_success:
  - Rscript -e 'covr::codecov()'
